<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.2" />
    <PackageReference Include="Microsoft.VisualStudio.DiagnosticsHub.BenchmarkDotNetDiagnosers" Version="18.7.37220.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CalradiaForge.Core\CalradiaForge.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core.Benchmarks\" />
    <Folder Include="Nexus.Benchmarks\" />
    <Folder Include="UI.Benchmarks\" />
  </ItemGroup>
</Project>
