<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DebugType>none</DebugType>
    <Title>CalradiaForge.Core</Title>
    <Authors>ThelianTech</Authors>
    <Copyright>Copyright © 2026 ThelianTech™</Copyright>
    <PackageProjectUrl>https://github.com/ThelianTech/CalradiaForge</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ThelianTech/CalradiaForge</RepositoryUrl>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
    <PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
    <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="SevenZipWrapper" Version="0.9.5-beta" />
  </ItemGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Debug'">
		<PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" PrivateAssets="all" />
	</ItemGroup>
	
</Project>
